highlighter: "rouge"
# - markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap

title: "John Barbic"
tagline: ""
description: "Follow <a href=\"https://micro.blog/johnbarbic\">@johnbarbic on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/johnbarbic\">@johnbarbic on Micro.blog</a>."
baseurl: ""
url: "http://www.barbic.com"
markdown: "kramdown"
username: "johnbarbic"
microblog_user: "johnbarbic"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "John Barbic"
name: "John Barbic"
gravatar_hash: "29dded88a1d07b81942d20a4c22e21d6"
avatar: "https://micro.blog/johnbarbic/avatar.jpg"
full_name: "John Barbic"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Mountain"
site_id: "1213"
gems: ["jekyll-paginate"]
itunes_description: ""
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "John Barbic"
itunes_email: ""
podcast: false